from __future__ import annotations

import re
from pathlib import Path

from .world import CollisionWorld, GfxWorld


def _quoted(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _safe_name(value: str, fallback: str) -> str:
    cleaned = re.sub(r"[^A-Za-z0-9_./,@+-]", "_", value)
    return cleaned or fallback


def _numbers(values) -> str:
    return ",".join(f"{value:.9g}" if isinstance(value, float) else str(value) for value in values)


MERGE_BUCKET = 1024.0
# Stock zm_nuked's largest world surface: 1536 tris / 1122 verts. Merged
# surfaces of ~15-19k verts overflow a fixed per-draw renderer buffer (access
# violation at a page boundary after running around a while).
MAX_MESH_TRIS = 1536
MAX_MESH_VERTS = 1536


def merge_surfaces(world: GfxWorld) -> list[tuple[str, list, int]]:
    """Group WaW surfaces into meshes by material, lightmap page and 1024-unit spatial bucket.

    WaW splits surfaces per lightmap page and cell; meshes keep the page (it
    becomes the T6 surface's lightmap) but not the cell: ~15k separate surfaces overflow BO2's
    per-frame draw lists (distant geometry vanishes, then the game crashes).
    Buckets keep meshes spatially compact so AABB-tree culling still works;
    caps keep each mesh within stock surface sizes."""
    buckets: dict[tuple, list] = {}
    for surface in world.surfaces:
        centre = tuple((surface.mins[k] + surface.maxs[k]) * 0.5 for k in range(3))
        key = (surface.material, surface.lightmap_index, *(int(c // MERGE_BUCKET) for c in centre))
        buckets.setdefault(key, []).append(surface)
    meshes: list[tuple[str, list]] = []
    for key in sorted(buckets, key=str):
        chunk, tris, verts = [], 0, 0
        for surface in buckets[key]:
            used = len({i for i in world.indices[surface.base_index: surface.base_index + surface.triangle_count * 3]})
            if chunk and (tris + surface.triangle_count > MAX_MESH_TRIS or verts + used > MAX_MESH_VERTS):
                meshes.append((key[0], chunk, key[1]))
                chunk, tris, verts = [], 0, 0
            chunk.append(surface)
            tris += surface.triangle_count
            verts += used
        if chunk:
            meshes.append((key[0], chunk, key[1]))
    return meshes


def write_world_fbx(world: GfxWorld, path: Path, blend_data_materials: frozenset[str] = frozenset()) -> None:
    """Write the WaW world as merged meshes (see merge_surfaces), preserving UV seams and materials.

    The T6 BSP loader expects Blender-style right-handed Y-up coordinates and
    applies its own transform.  WaW/BO2 coordinates are converted inversely.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    material_names = sorted({surface.material for surface in world.surfaces})
    material_ids = {name: 2_000_000 + i for i, name in enumerate(material_names)}
    meshes = merge_surfaces(world)
    with path.open("w", encoding="utf-8", newline="\n") as out:
        out.write("; FBX 7.4.0 project file generated by waw2bo2\nFBXHeaderExtension: {\n FBXHeaderVersion: 1003\n FBXVersion: 7400\n}\n")
        out.write("GlobalSettings: {\n Version: 1000\n Properties70: {\n  P: \"UpAxis\", \"int\", \"Integer\", \"\",1\n  P: \"UpAxisSign\", \"int\", \"Integer\", \"\",1\n  P: \"FrontAxis\", \"int\", \"Integer\", \"\",2\n  P: \"FrontAxisSign\", \"int\", \"Integer\", \"\",-1\n  P: \"CoordAxis\", \"int\", \"Integer\", \"\",0\n  P: \"CoordAxisSign\", \"int\", \"Integer\", \"\",1\n  P: \"UnitScaleFactor\", \"double\", \"Number\", \"\",1\n }\n}\n")
        out.write("Objects:  {\n")
        for i, (material, group, lightmap) in enumerate(meshes):
            geom_id, model_id = 10_000 + i * 2, 10_001 + i * 2
            # firstVertex/vertexCount describe a backing-buffer span, not a
            # promise that every vertex in that span is referenced.  Some T4
            # worlds contain very large sparse spans. Compact only referenced
            # vertices or an otherwise lossless export can grow by gigabytes.
            used: dict[int, int] = {}
            compact_indices: list[int] = []
            for surface in group:
                for source_index in world.indices[surface.base_index : surface.base_index + surface.triangle_count * 3]:
                    compact_indices.append(used.setdefault(surface.first_vertex + source_index, len(used)))
            verts = [world.vertices[absolute] for absolute in used]
            surface = group[0]
            positions = []
            normals = []
            tangents = []
            binormals = []
            colors = []
            uvs = []
            lightmap_uvs = []
            for v in verts:
                positions.extend((v.xyz[0], v.xyz[2], -v.xyz[1]))
                n = (v.normal[0], v.normal[2], -v.normal[1])
                t = (v.tangent[0], v.tangent[2], -v.tangent[1])
                normals.extend(n)
                tangents.extend(t)
                # WaW binormal = binormalSign * cross(normal, tangent); the axis
                # swap is a rotation, so the cross product carries over
                sign = -1.0 if v.binormal_sign < 0 else 1.0
                binormals.extend(sign * c for c in (n[1] * t[2] - n[2] * t[1], n[2] * t[0] - n[0] * t[2],
                                                    n[0] * t[1] - n[1] * t[0]))
                # vertex colour; alpha drives the layer blend of WaW "*" materials
                # layered WaW surfaces keep their blend weight in the vertex
                # colour (green); drawn as their base layer it must not tint
                colors.extend((1.0, 1.0, 1.0, 1.0) if surface.material in blend_data_materials else v.color)
                uvs.extend((v.uv[0], 1.0 - v.uv[1]))
                lightmap_uvs.extend((v.lightmap_uv[0], 1.0 - v.lightmap_uv[1]))
            # The bridge reverses every triangle (it assumes Blender's CCW
            # winding). WaW triangles already use BO2's winding, so write them
            # reversed here; otherwise every surface is back-face culled.
            polygons = []
            for j in range(0, len(compact_indices), 3):
                a, b, c = compact_indices[j : j + 3]
                polygons.extend((a, c, -b - 1))
            # the lightmap page travels in the name (read back by the bridge's BSPCreator)
            name = f"waw_mesh_{i:05d}_lm{lightmap}"
            out.write(f" Geometry: {geom_id}, {_quoted('Geometry::' + name)}, \"Mesh\" {{\n")
            out.write(f"  Vertices: *{len(positions)} {{ a: {_numbers(positions)} }}\n")
            out.write(f"  PolygonVertexIndex: *{len(polygons)} {{ a: {_numbers(polygons)} }}\n")
            out.write("  GeometryVersion: 124\n")
            out.write("  LayerElementNormal: 0 {\n   Version: 101\n   Name: \"\"\n   MappingInformationType: \"ByVertice\"\n   ReferenceInformationType: \"Direct\"\n")
            out.write(f"   Normals: *{len(normals)} {{ a: {_numbers(normals)} }}\n  }}\n")
            out.write("  LayerElementTangent: 0 {\n   Version: 101\n   Name: \"\"\n   MappingInformationType: \"ByVertice\"\n   ReferenceInformationType: \"Direct\"\n")
            out.write(f"   Tangents: *{len(tangents)} {{ a: {_numbers(tangents)} }}\n  }}\n")
            out.write("  LayerElementBinormal: 0 {\n   Version: 101\n   Name: \"\"\n   MappingInformationType: \"ByVertice\"\n   ReferenceInformationType: \"Direct\"\n")
            out.write(f"   Binormals: *{len(binormals)} {{ a: {_numbers(binormals)} }}\n  }}\n")
            out.write("  LayerElementColor: 0 {\n   Version: 101\n   Name: \"\"\n   MappingInformationType: \"ByVertice\"\n   ReferenceInformationType: \"Direct\"\n")
            out.write(f"   Colors: *{len(colors)} {{ a: {_numbers(colors)} }}\n  }}\n")
            out.write("  LayerElementUV: 0 {\n   Version: 101\n   Name: \"UVChannel_1\"\n   MappingInformationType: \"ByVertice\"\n   ReferenceInformationType: \"Direct\"\n")
            out.write(f"   UV: *{len(uvs)} {{ a: {_numbers(uvs)} }}\n  }}\n")
            out.write("  LayerElementUV: 1 {\n   Version: 101\n   Name: \"LightmapUV\"\n   MappingInformationType: \"ByVertice\"\n   ReferenceInformationType: \"Direct\"\n")
            out.write(f"   UV: *{len(lightmap_uvs)} {{ a: {_numbers(lightmap_uvs)} }}\n  }}\n")
            out.write("  LayerElementMaterial: 0 {\n   Version: 101\n   Name: \"\"\n   MappingInformationType: \"AllSame\"\n   ReferenceInformationType: \"IndexToDirect\"\n   Materials: *1 { a: 0 }\n  }\n")
            out.write("  Layer: 0 {\n   Version: 100\n   LayerElement: { Type: \"LayerElementNormal\"\n    TypedIndex: 0\n   }\n   LayerElement: { Type: \"LayerElementTangent\"\n    TypedIndex: 0\n   }\n   LayerElement: { Type: \"LayerElementBinormal\"\n    TypedIndex: 0\n   }\n   LayerElement: { Type: \"LayerElementColor\"\n    TypedIndex: 0\n   }\n   LayerElement: { Type: \"LayerElementMaterial\"\n    TypedIndex: 0\n   }\n   LayerElement: { Type: \"LayerElementUV\"\n    TypedIndex: 0\n   }\n  }\n  Layer: 1 {\n   Version: 100\n   LayerElement: { Type: \"LayerElementUV\"\n    TypedIndex: 1\n   }\n  }\n }")
            out.write(f"\n Model: {model_id}, {_quoted('Model::' + name)}, \"Mesh\" {{\n  Version: 232\n  Properties70: {{\n   P: \"Lcl Scaling\", \"Lcl Scaling\", \"\", \"A\",100,100,100\n  }}\n  Shading: T\n  Culling: \"CullingOff\"\n }}\n")
        for name, material_id in material_ids.items():
            out.write(f" Material: {material_id}, {_quoted('Material::' + name)}, \"\" {{\n  Version: 102\n  ShadingModel: \"phong\"\n  MultiLayer: 0\n }}\n")
        out.write("}\nConnections:  {\n")
        for i, (material, _group, _lightmap) in enumerate(meshes):
            geom_id, model_id = 10_000 + i * 2, 10_001 + i * 2
            out.write(f" C: \"OO\",{geom_id},{model_id}\n C: \"OO\",{model_id},0\n C: \"OO\",{material_ids[material]},{model_id}\n")
        out.write("}\n")


def write_collision_fbx(collision: CollisionWorld, path: Path) -> None:
    """Write the original T4 collision triangles as one T6 BSP source mesh."""
    path.parent.mkdir(parents=True, exist_ok=True)
    used: dict[int, int] = {}
    compact_indices: list[int] = []
    for source_index in collision.indices:
        compact_indices.append(used.setdefault(source_index, len(used)))
    positions: list[float] = []
    for source_index in used:
        x, y, z = collision.vertices[source_index]
        positions.extend((x, z, -y))
    # BSPCreator.cpp reverses every FBX triangle when writing BO2 clipmap
    # indices. Preserve the WaW winding here so that its mostly downward-wound
    # terrain becomes upward-facing in the compiled clipmap. Reversing here as
    # well cancels the bridge reversal and leaves the floor non-solid from above.
    polygons = []
    for i in range(0, len(compact_indices), 3):
        a, b, c = compact_indices[i : i + 3]
        # Reversed for the bridge exactly like the render triangles: WaW
        # already uses BO2's winding and the bridge flips every triangle. T6
        # terrain collision is one-sided; with the wrong winding players sink
        # through the ground. (An earlier test suggesting the opposite ran
        # while the collision tree indices were overflowing, so it proved nothing.)
        polygons.extend((a, c, -b - 1))
    uvs = [0.0] * (len(used) * 2)
    with path.open("w", encoding="utf-8", newline="\n") as out:
        out.write("; FBX 7.4.0 project file generated by waw2bo2\nFBXHeaderExtension: {\n FBXHeaderVersion: 1003\n FBXVersion: 7400\n}\n")
        out.write("GlobalSettings: {\n Version: 1000\n Properties70: {\n  P: \"UpAxis\", \"int\", \"Integer\", \"\",1\n  P: \"UpAxisSign\", \"int\", \"Integer\", \"\",1\n  P: \"FrontAxis\", \"int\", \"Integer\", \"\",2\n  P: \"FrontAxisSign\", \"int\", \"Integer\", \"\",-1\n  P: \"CoordAxis\", \"int\", \"Integer\", \"\",0\n  P: \"CoordAxisSign\", \"int\", \"Integer\", \"\",1\n  P: \"UnitScaleFactor\", \"double\", \"Number\", \"\",1\n }\n}\n")
        out.write("Objects: {\n Geometry: 10000, \"Geometry::waw_collision\", \"Mesh\" {\n")
        out.write(f"  Vertices: *{len(positions)} {{ a: {_numbers(positions)} }}\n")
        out.write(f"  PolygonVertexIndex: *{len(polygons)} {{ a: {_numbers(polygons)} }}\n")
        out.write("  GeometryVersion: 124\n  LayerElementUV: 0 {\n   Version: 101\n   Name: \"UVChannel_1\"\n   MappingInformationType: \"ByVertice\"\n   ReferenceInformationType: \"Direct\"\n")
        out.write(f"   UV: *{len(uvs)} {{ a: {_numbers(uvs)} }}\n  }}\n")
        out.write("  LayerElementMaterial: 0 {\n   Version: 101\n   Name: \"\"\n   MappingInformationType: \"AllSame\"\n   ReferenceInformationType: \"IndexToDirect\"\n   Materials: *1 { a: 0 }\n  }\n")
        out.write("  Layer: 0 {\n   Version: 100\n   LayerElement: {\n    Type: \"LayerElementMaterial\"\n    TypedIndex: 0\n   }\n   LayerElement: {\n    Type: \"LayerElementUV\"\n    TypedIndex: 0\n   }\n  }\n }\n")
        out.write(" Model: 10001, \"Model::waw_collision\", \"Mesh\" {\n  Version: 232\n  Properties70: {\n   P: \"Lcl Scaling\", \"Lcl Scaling\", \"\", \"A\",100,100,100\n  }\n  Shading: T\n  Culling: \"CullingOff\"\n }\n")
        out.write(" Material: 20000, \"Material::waw_collision\", \"\" {\n  Version: 102\n  ShadingModel: \"phong\"\n  MultiLayer: 0\n }\n}\n")
        out.write("Connections: {\n C: \"OO\",10000,10001\n C: \"OO\",10001,0\n C: \"OO\",20000,10001\n}\n")

